<a href="https://colab.research.google.com/github/Dnishkala/internship/blob/master/ML5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python scikit learn

In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
demoData = np.random.randint(10, 100, (10 ,2))
demoData

array([[92, 80],
       [39, 47],
       [42, 81],
       [79, 17],
       [11, 96],
       [16, 57],
       [90, 78],
       [63, 69],
       [92, 12],
       [55, 43]])

In [5]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
demoData = np.random.randint(1, 500, (20 ,4))
demoData

array([[328, 383,  12, 397],
       [268,  97, 469, 311],
       [ 39, 117, 297, 466],
       [195, 396,  26, 318],
       [308, 368, 314, 394],
       [ 42,  20, 436, 111],
       [182, 371, 377,  41],
       [ 38,  25, 278, 454],
       [209, 265, 346,  76],
       [288,  52, 330, 494],
       [339, 290, 276, 375],
       [189, 233, 418,  76],
       [197, 456, 166, 422],
       [492, 281, 162,  36],
       [ 34, 335, 300, 342],
       [257, 210, 101,  48],
       [ 16, 286, 100, 251],
       [305,  80, 198, 387],
       [263, 321, 298, 211],
       [319,  28, 207, 327]])

In [6]:
scalar_model = MinMaxScaler()
feature_data = scalar_model.fit_transform(demoData)
feature_data

array([[0.65546218, 0.83256881, 0.        , 0.78820961],
       [0.52941176, 0.1766055 , 1.        , 0.60043668],
       [0.04831933, 0.22247706, 0.62363239, 0.93886463],
       [0.37605042, 0.86238532, 0.03063457, 0.61572052],
       [0.61344538, 0.79816514, 0.66083151, 0.78165939],
       [0.05462185, 0.        , 0.92778993, 0.16375546],
       [0.3487395 , 0.80504587, 0.79868709, 0.01091703],
       [0.04621849, 0.01146789, 0.58205689, 0.91266376],
       [0.40546218, 0.56192661, 0.73085339, 0.08733624],
       [0.57142857, 0.0733945 , 0.69584245, 1.        ],
       [0.67857143, 0.61926606, 0.57768053, 0.74017467],
       [0.36344538, 0.48853211, 0.88840263, 0.08733624],
       [0.3802521 , 1.        , 0.33698031, 0.84279476],
       [1.        , 0.59862385, 0.32822757, 0.        ],
       [0.03781513, 0.72247706, 0.63019694, 0.66812227],
       [0.50630252, 0.43577982, 0.19474836, 0.02620087],
       [0.        , 0.61009174, 0.19256018, 0.46943231],
       [0.60714286, 0.13761468,

In [7]:
import pandas as pd
df = pd.DataFrame(data=feature_data, columns=['k1', 'k2', 'k3', 'labels'])
df

k1        k2        k3    labels
0   0.655462  0.832569  0.000000  0.788210
1   0.529412  0.176606  1.000000  0.600437
2   0.048319  0.222477  0.623632  0.938865
3   0.376050  0.862385  0.030635  0.615721
4   0.613445  0.798165  0.660832  0.781659
5   0.054622  0.000000  0.927790  0.163755
6   0.348739  0.805046  0.798687  0.010917
7   0.046218  0.011468  0.582057  0.912664
8   0.405462  0.561927  0.730853  0.087336
9   0.571429  0.073394  0.695842  1.000000
10  0.678571  0.619266  0.577681  0.740175
11  0.363445  0.488532  0.888403  0.087336
12  0.380252  1.000000  0.336980  0.842795
13  1.000000  0.598624  0.328228  0.000000
14  0.037815  0.722477  0.630197  0.668122
15  0.506303  0.435780  0.194748  0.026201
16  0.000000  0.610092  0.192560  0.469432
17  0.607143  0.137615  0.407002  0.766376
18  0.518908  0.690367  0.625821  0.382096
19  0.636555  0.018349  0.426696  0.635371

In [9]:
X = df[['k1', 'k2', 'k3']]
y = df['labels']
X

k1        k2        k3
0   0.655462  0.832569  0.000000
1   0.529412  0.176606  1.000000
2   0.048319  0.222477  0.623632
3   0.376050  0.862385  0.030635
4   0.613445  0.798165  0.660832
5   0.054622  0.000000  0.927790
6   0.348739  0.805046  0.798687
7   0.046218  0.011468  0.582057
8   0.405462  0.561927  0.730853
9   0.571429  0.073394  0.695842
10  0.678571  0.619266  0.577681
11  0.363445  0.488532  0.888403
12  0.380252  1.000000  0.336980
13  1.000000  0.598624  0.328228
14  0.037815  0.722477  0.630197
15  0.506303  0.435780  0.194748
16  0.000000  0.610092  0.192560
17  0.607143  0.137615  0.407002
18  0.518908  0.690367  0.625821
19  0.636555  0.018349  0.426696

In [10]:
X = df[['k1', 'k2', 'k3']]
y = df['labels']
y

0     0.788210
1     0.600437
2     0.938865
3     0.615721
4     0.781659
5     0.163755
6     0.010917
7     0.912664
8     0.087336
9     1.000000
10    0.740175
11    0.087336
12    0.842795
13    0.000000
14    0.668122
15    0.026201
16    0.469432
17    0.766376
18    0.382096
19    0.635371
Name: labels, dtype: float64

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)
X_train.shape

(14, 3)

In [14]:
from sklearn.datasets import load_iris
iris=load_iris()
type(iris)
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [16]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [15]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
