<a href="https://colab.research.google.com/github/Dnishkala/internship/blob/master/PAP3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
isinstance(4, object)

True

Objects

In [2]:
isinstance("Hello", object)

True

In [3]:
isinstance(None, object)

True

In [4]:
isinstance([1,2,3], object)

True

In [7]:
import numpy as np
a=np.arange(15).reshape(3, 5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
a.shape

(3, 5)

In [9]:
a.ndim

2

In [10]:
a.dtype.name

'int64'

In [11]:
a.itemsize

8

In [12]:
a.size

15

In [13]:
type(a)

numpy.ndarray

In [20]:
import numpy as np
c=np.arange(18).reshape(2, 3, 3)
c


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [21]:
c.ndim

3

In [22]:
c.shape

(2, 3, 3)

In [23]:
c.dtype.name

'int64'

Array creation

In [24]:
import numpy as np
d=np.array([2,3,4])
d

array([2, 3, 4])

In [25]:
d.dtype

dtype('int64')

In [26]:
e=np.array([1.2, 3.5, 5.1])
e.dtype

dtype('float64')

In [27]:
e=np.array([(1.5,2,3), (4,5,6)])
e

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [30]:
f=np.array([[1,2], [3,4]], dtype=complex)
f

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Creating zeros

In [31]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
np.zeros((4,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

generation ones

In [33]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [37]:
np.empty( (1,3) )

array([[1.2, 3.5, 5.1]])

In [41]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [42]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])